/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/desk-view': RouteRecordInfo<'/desk-view', '/desk-view', Record<never, never>, Record<never, never>>,
    '/desktop-view': RouteRecordInfo<'/desktop-view', '/desktop-view', Record<never, never>, Record<never, never>>,
    '/portfolio/': RouteRecordInfo<'/portfolio/', '/portfolio', Record<never, never>, Record<never, never>>,
    '/toys/': RouteRecordInfo<'/toys/', '/toys', Record<never, never>, Record<never, never>>,
    '/toys/emojiGrid': RouteRecordInfo<'/toys/emojiGrid', '/toys/emojiGrid', Record<never, never>, Record<never, never>>,
  }
}
